services:
  dashy:
    image: lissy93/dashy
    container_name: dashy
    ports:
      - 4000:8080
    #environment:
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "/app/services/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 40s